### ISSUE TITLE
Fehler bei Skriptausführung - was ist die Ursache?

### ISSUE THREAD

**Issue by LK1976** [gsicilia82/Timer_iobroker#5]
Guten Morgen,

seit Stunden versuche ich das Skript ohne Fehler ans Laufen zu bekommen, leider bisher erfolglos.

Hast Du eine Ahnung, wieso diese Fehlermeldung kommt? Wie kann ich das Problem lösen?

![grafik](https://user-images.githubusercontent.com/121298651/209413251-573e56ab-1057-4c01-8007-d80d397aaff4.png)

**Comment by gsicilia82** [comment]
Am besten bitte die Fehlermeldungen aus dem log Fenster kopieren. Da stehen für gewöhnlich mehr Fehlerzeilen. Ein Screenshot reicht hier auch aus. 

In der Zwischenzeit: bitte sicherstellen, dass wirklich nur States in den Aufzählungen vorhanden sind, keine Channels oder ähnliches. D.h. keine übergeordnete Ordner in den Aufzählungen.

**Comment by gsicilia82** [comment]
Ein Versuch wäre es auch wert, die erste Aufzählung umzubenennen, dass keine deutschen Umlaute verwendet werden. Umlaute innerhalb funktionalen Bezeichnungen ist nie eine gute Idee. Kann aber bis zum neuen Jahr nicht testen ob es daran liegt, weil ich nicht daheim bin.

**Comment by LK1976** [comment]
Vielen Dank für Deine ersten Tipps. Das Umbenennen der Umlaute im Funktionsnamen und anschließendem Neustart brachte nicht den gewünschten Erfolg, der Fehler ist geblieben. Hier der Auszug aus dem Protokoll:

![grafik](https://user-images.githubusercontent.com/121298651/209431934-f21dd8bd-6c8a-4d25-abbc-69eb90f9af74.png)

Hast Du vielleicht noch eine Idee, wie wir das gelöst bekommen?

**Comment by gsicilia82** [comment]
Die nächsten Tage bin ich nicht am PC. Aufgrund der Feiertage bin ich unterwegs.
Prüfe bitte, ob die States in deinen Aufzählungen noch tatsächlich existieren und ob es wirklich States, d.h. Endpunkte sind. Übergeordnete Ordner können nicht verarbeitet werden.
Ohne PC kann ich auch nicht prüfen, wie ich die Eingangswerte abgesichert habe. Der Code ist auf dem Smartphone doch ziemlich lang 😉
Am besten prüfst du die genannten Punkte ab und startest bei 0. D.h. alle automatisch erstellten States löschen (falls bereits etwas erstellt wurde) und so wenig wie möglich anpassen. Zunächst nur die oberen zwei Aufzählungen einstellen.
Ich kann mir nicht vorstellen, dass sich ein Fehler im Skript eingeschlichen hat, da ich schon länger nichts angepasst habe.

**Comment by LK1976** [comment]
In den Aufzählungen sind nur States, also Endpunkte, KEINE übergeordneten Ordner.

Auch existieren alle States auch noch und sind auch grundsätzlich funktional, die Objekteinträge verändern sich je nach Zustand.

Ich habe bei Null angefangen und erhalte trotzdem die o. g. Fehlermeldungen. Somit glaube ich, dass es vielleicht doch am Code liegt? Auf jeden Fall weiß ich mir nicht mehr zu helfen und hoffe, nach den Feiertagen, auf Deine Hilfe. Vorab vielen Dank!

**Comment by LK1976** [comment]
Gsicilia82, magst Du einmal schauen, wenn Du Zeit hast? Wäre Dir echt dankbar 😉

**Comment by gsicilia82** [comment]
Hey, bin seit heute Abend erst wieder daheim. Hatte mir bereits eine Notiz gemacht, am PC zunächst das Skript zu testen. Das werde ich morgen auf jeden Fall machen und mich melden.

**Comment by gsicilia82** [comment]
Habe das Skript original kopiert und bei mir hinzugefügt. Log schaut wie folgt aus (keine Fehler):

![image](https://user-images.githubusercontent.com/62556925/210244599-bd11b454-c10f-460d-98bd-5d29cc16f5e8.png)


Nach dem ersten Start sollte die Meldung kommen, dass das Skript bitte nochmals neugestartet werden soll.

Edit:
Habe nun zwei neue, leere Aufzählungen oben im Skript eingestellt. Da bekomme ich nun auch Fehlermeldungen, die deinen Fehlern entsprechen. Sind deine Aufzählungen leer?

**Comment by LK1976** [comment]
Hallo gsicilia82,

erst einmal ein frohes neues Jahr verbunden mit dem Dank, dass Du Dich bemühst mein Problem zu lösen.

Ich habe die V1.3.3 installiert, aber leider keine Veränderung (Problemlösung) feststellen können.

Nach wie vor sieht der Log wie folgt aus:

2.1.2023, 17:35:25.468	[info ]: javascript.0 (66788) Stop script script.js.Zeitschaltuhr_gsicilia82
2.1.2023, 17:35:25.544	[info ]: javascript.0 (66788) Start javascript script.js.Zeitschaltuhr_gsicilia82
2.1.2023, 17:35:25.570	[info ]: javascript.0 (66788) script.js.Zeitschaltuhr_gsicilia82: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
2.1.2023, 17:35:27.075	[info ]: javascript.0 (66788) script.js.Zeitschaltuhr_gsicilia82: Veränderte ObjID entdeckt: ALT = alias.0.Steckdosen.Steckdose_Reserve_2.SET | NEU = alias.0.Steckdosen.Steckdose_Reserve_1.SET
2.1.2023, 17:35:27.076	[info ]: javascript.0 (66788) script.js.Zeitschaltuhr_gsicilia82: Veränderte ObjID entdeckt: ALT = alias.0.Steckdosen.Steckdose_Reserve_2.SET | NEU = alias.0.Steckdosen.Steckdose_Reserve_1.SET
2.1.2023, 17:35:27.076	[info ]: javascript.0 (66788) script.js.Zeitschaltuhr_gsicilia82: Veränderte ObjID entdeckt: ALT = alias.0.Steckdosen.Steckdose_Reserve_1.SET | NEU = alias.0.Steckdosen.Steckdose_Reserve_2.SET
2.1.2023, 17:35:27.077	[info ]: javascript.0 (66788) script.js.Zeitschaltuhr_gsicilia82: Veränderte ObjID entdeckt: ALT = alias.0.Steckdosen.Steckdose_Reserve_1.SET | NEU = alias.0.Steckdosen.Steckdose_Reserve_2.SET
2.1.2023, 17:35:29.084	[error]: javascript.0 (66788)     at buildTableArray (script.js.Zeitschaltuhr_gsicilia82:1621:37)
2.1.2023, 17:35:29.085	[error]: javascript.0 (66788)     at Object.<anonymous> (script.js.Zeitschaltuhr_gsicilia82:1874:23)

bzw.

![grafik](https://user-images.githubusercontent.com/121298651/210258618-bcce7871-890d-4523-b3ee-6e21f4de44d8.png)

Die Aufzählungen sehen bei mir wie folgt aus und sind nach meinem Verständnis nicht leer:

![grafik](https://user-images.githubusercontent.com/121298651/210258801-a1a315db-b7f2-4b0a-9dc8-e6844e0fe292.png)

Findest Du den Fehler?

**Comment by LK1976** [comment]
Ich glaube, ich habe den "Fehler" (es lag an mir) gefunden. Ich habe einmal die Objekte im Knoten Javascript gelöscht, neu anlegen lassen und nun scheint es ohne Fehler zu funktionieren. Ich teste nun und würde mich dann danach noch einmal melden.

**Comment by LK1976** [comment]
Nun klappt alles, vielen Dank!
