### ISSUE TITLE
Wie realisiere ich den folgenden Anwendungsfall?

### ISSUE THREAD

**Issue by LK1976** [gsicilia82/Timer_iobroker#6]
Hallo Gsicilia82,

zwischenzeitlich habe ich bereits eine Schaltungen mit Deinem Skript vornehmen können. Nun hänge ich jedoch an folgendem Problem:

Ich möchte, dass wenn keiner mehr zu Hause ist, abends eine Steckdose geschaltet wird (TV-Simulator). Dazu habe ich eine Bedingung, die zuverlässig prüft, ob noch Handys im WLAN sind? Somit klappt die Schaltung grundsätzlich.

Ich schalte die Steckdose somit um 18 Uhr an, mit der Bedingung und laufendem Timer, dass bei "nicht anwesend = true" das Einschalten dieser Steckdose erfolgt. Es wird also ab 18 Uhr geprüft, ob ich das Haus verlasse und dann wird die Steckdose geschaltet.
 
Gleichzeitig soll aber ein Timer mit der selben Steckdose laufen, der prüft, ob ich nicht nach Hause komme und somit die Steckdose ausgeschaltet werden müsste. Aktuell beenden sich diese beiden Timer gegenseitig, da sie sich auf die selbe Steckdose beziehen. Also das Prüfen auf Rückkehr kollidiert mit dem Timer auf Prüfen des Hausverlassens.

Hast Du eine Idee, wie ich das gelöst bekomme?

**Comment by gsicilia82** [comment]
Hi,

Du hast absolut Recht. Ein nachfolgender Timer "beendet" immer den vorhergehenden Timer. Da die Timer eine "merken"-Funktion haben, wollte ich es irgendwie komfortabel lösen, dass gemerkte Timer gestoppt werden.

Deine Funktionalität ist somit aktuell nicht möglich. Allerdings habe ich selbiges Thema (ähnlich) anders gelöst:
Wenn ich nach Hause komme, wird immer eine Szene getriggert. Diese führt dann entsprechende Aktionen aus, wie z.B. Licht einschalten. In deinem Fall wäre es Anwesenheits-Simulatoren auszuschalten.
Wenn ich das Haus verlassen, wird übrigens auch eine Szene getriggert, diese schaltet alle Lichter aus etc.

Gruß,
Giuseppe

**Comment by LK1976** [comment]
Vielen Dank für Deine Antwort.

Ich hatte mir zwischenzeitlich überlegt, dass wenn ich von der Steckdose einen Alias anlege, der dann logischer Weise anders benannt wird, kann ich damit Deine Programmierung nicht austricksen und doch mehrere Timer für letztendlich ein und dasselbe Gerät parrallel laufen lassen?

Aktuell habe ich aber noch eine andere Auffälligkeit:

Das Aktivieren/Deaktivieren von Timern funktioniert nicht zuverlässig:

![grafik](https://user-images.githubusercontent.com/121298651/210429636-72f20511-bb75-4247-92d7-3cfa06fef65f.png)
 
Eigentlich dürfte es denn Zustand, alle Timer aktiv, aber unten dann doch keine nächste Aktivität ausstehend, gar nicht geben. Wenn ich die Timer mit Doppelklick deaktiviere, dann werden Sie zwar als deaktiviert angezeigt, aber nach einem refresh der Internetseite sind sie dann doch wieder aktiv oder auch nicht. Hast Du das auch?

**Comment by gsicilia82** [comment]
Mit deinem Vorschlag bzgl Alias kannst du die Programmierung umgehen.
Zu diesem Punkt ein Hinweis: Gemerkte Timer werden "beendet", sobald sich der Status des Zielgeräts ändert. Wenn du ein Gerät unter verschiedenen Namen anlegst und ein Timer aktiv auslöst, d.h. der Zustand des Zielgeräts wird verändert, dann werden auch eventuell schlummernde Timer beendet.

Aktivieren und Deaktivieren von Timern geht über einfache Klicks (=Srandard) der Symbole oder der Ziffern. Im Skript kann es auf Doppelklick umgestellt werden. Das funktioniert absolut zuverlässig.

**Comment by gsicilia82** [comment]
Dass unten kein nächster Timer angezeigt wird, obwohl oben alle aktiv sind, müsste ich mal prüfen. Das wird über cron aktualisiert, evtl etwas warten.

**Comment by LK1976** [comment]
Problem ist, dass nachdem ich die VIS Ansicht erneut aufrufe, die vermeintlich aktivierten Timer dann wieder auf deaktiviert stehen. Mit freundlichen GrüßenLars KroszewskiE-Mail: ***@***.*** 03.01.2023 um 21:23 schrieb gsicilia82 ***@***.***>:﻿
Dass unten kein nächster Timer angezeigt wird, obwohl oben alle aktiv sind, müsste ich mal prüfen. Das wird über cron aktualisiert, evtl etwas warten.

**Comment by LK1976** [comment]
Im Log steht, dass die Timer gelöscht wurden:

![grafik](https://user-images.githubusercontent.com/121298651/210439454-682d5f21-feba-4d3b-b5ce-496a20f61c78.png)

Wenn ich VID erneut aufrufe, sind optisch aber alle aktiviert?!

**Comment by gsicilia82** [comment]
Welchen Browser verwendest du? Auf dem Handy mit Chrome und Firefox und ebenfalls am Tablet mit Fullybrowser kann ich dieses Verhalten nicht nachvollziehen.
Kannst du bitte an einem anderen PC o.ä. prüfen ob es das selbe Verhalten ist?
Wenn du die Timer aktivierst, siehst du dann auch eine Meldung im Log?

**Comment by gsicilia82** [comment]
So schaut es aus, wenn man deaktiviert und wieder aktiviert

![Screenshot_20230103-215706](https://user-images.githubusercontent.com/62556925/210440341-33d7a3d0-3821-48b0-9853-de3d3db262b2.png)

**Comment by LK1976** [comment]
Ich verwende an beiden PCs Firefox ... Ja, es wird der Wechsel im Log vollzogen. Nur dadurch, dass die Ansicht teilweise durcheinander ist, kann ich optisch nicht mit Gewissheit sagen, ob jetzt aktiviert oder deaktiviert wurde. Eben war es so, als ich die Haken weggemacht habe, der dazugehörige Log von Aktivierung gesprochen hat, obwohl es ja optisch deaktiviert wurde.

**Comment by LK1976** [comment]
Deaktiviere doch bitte mal Deine Timer, dann verschwinden optisch die Haken, dann wird gelöscht ... geloggt. Und aktualisiere dann mal die VIS Ansicht und die Haken sind wieder da, obwohl der Timer gelöscht ist ...

Bei mir ist es so, bei Dir nicht?

**Comment by gsicilia82** [comment]
Bei mir funktioniert alles einwandfrei. Und auch bei allen anderen Anwendern. Im Forum hatte ich ein paar User erreicht, die es nutzen oder zumindest genutzt hatten. So ein Fehler wäre aufgefallen.

Du schreibst, dass die Ansicht teilweise durcheinander ist. Die Ansicht in der Tabelle ist immer gleich.
Starte bitte bei null und befolge diese Schritte Punkt für Punkt:

* Stoppe das Skript
* Lösche alle States vom Skript unter der JavaScript Instanz
* Starte das Skript neu
* Aktiviere einen einzigen Timer mit einem Klick auf dem Symbol oder auf die Timernummer. VIS Seite nicht neu laden. 
* Siehst Du den Eintrag im Log?
* Wenn Du deaktivierst, siehst Du den Log Eintrag?
* Passt bis hierhin alles? Darstellung und realer Zustand laut Log?

Ich hatte übrigens in einem deiner älteren Screenshots gesehen, dass du in den Aufzählungen States hattest, die den selben Namen haben. Das solltest du ändern, wenn du die States im Timer unterscheiden möchtest.

**Comment by LK1976** [comment]
Ich habe es genau so gemacht, wie Du geschrieben hast, also:

![grafik](https://user-images.githubusercontent.com/121298651/210448545-ea2caad2-00ce-4712-88ca-91ecfd678064.png)

![grafik](https://user-images.githubusercontent.com/121298651/210448695-d6461a3b-4e81-4ba0-a001-1302646d6917.png)

Ja, bis hierhin passt alles. Soll ich jetzt einmal die VIS Seite neu laden?

**Comment by LK1976** [comment]
Was "stört" Dich an meinen Aufzählungen konkret?

![grafik](https://user-images.githubusercontent.com/121298651/210449077-59509407-88db-4b37-91c1-9e31f3c2fa3d.png)

**Comment by LK1976** [comment]
Ich habe nun die VIS Seite einmal neu geladen und obwohl alle Timer deaktiviert sind, zeigt sie jetzt wieder einen Timer als aktiviert an:

![grafik](https://user-images.githubusercontent.com/121298651/210449377-e6ab642a-abb2-4d04-b32d-b3c83a9b872f.png)

**Comment by LK1976** [comment]
Kann es in der VIS Ansicht unten rechts an dem Haken bei "Zeige letzte Änderung" liegen? Bin ich da vielleicht versehentlich drauf gekommen? Hast Du den Haken dort auch?

![grafik](https://user-images.githubusercontent.com/121298651/210452185-ad4c3748-969b-4b45-8822-2b4f666bb11a.png)

**Comment by gsicilia82** [comment]
Das ist echt kurios... Der Haken unten rechts stört nicht. Den habe ich auch.

Habe es jetzt einfach mal getestet, wie du es machst und tatsächlich, die Anzeige zeigt wieder grün an, obwohl deaktiviert.
Es scheint aber ausschließlich beim Reload ein Problem zu sein. Wenn man die Seite schließt und dann neu aufruft passt es. Werde morgen etwas testen und mich melden.
Sorry, dass ich es nicht wahr haben konnte. Dachte Reload ist das selbe wie schließen/neu starten.

**Comment by gsicilia82** [comment]
Sooo.... Habe nun ein Bugfix hochgeladen. Es war eigentlich ziemlich simpel zu lösen.

Ursprüngliche Idee war:
Wenn ein Timer aktiviert/deaktiviert wird, soll sich nicht die gesamte Tabelle aktualisieren. Wenn nämlich gescrollt wurde, landet man wieder ganz oben. Daher führte das Aktivieren/Deaktivieren der Timer nicht mehr zum Aktualisieren der Gesamttabelle. Es muss irgendwann mit einem der letzten Updates passiert sein.

Bugfix:
Aktualisieren der Tabelle findet nun nach 2 Sekunden statt. Wenn in der Tabelle gescrollt wurde, können somit immer weitere Timer aus dem unteren Bereich verändert werden bis 2 Sekunden nach der letzten Änderung die Tabelle aktualisiert wird.


Für dich:
Du kannst das letzte Skript übernehmen und testen. Wenn das Skript gestoppt und neu gestartet wird, wird immer die HTML Tabelle generiert. Daher musst du nicht darauf achten, ob der angezeigte Zustand tatsächlich übereinstimmt. Ein Reload der Seite nach 2 Sekunden sollte nun die korrekten Statis anzeigen. Bitte um Rückmeldung, wenn Test durchgeführt wurde.

**Comment by LK1976** [comment]
Hallo Giuseppe,

die Aktualisierung der Gesamttabelle (der Bug) ist erfolgreich von Dir gelöst worden. Dafür vielen Dank!

Du hattest mir zu meiner Idee mit den Alias folgendes geschrieben:

_Mit deinem Vorschlag bzgl Alias kannst du die Programmierung umgehen.
Zu diesem Punkt ein Hinweis: Gemerkte Timer werden "beendet", sobald sich der Status des Zielgeräts ändert. Wenn du ein Gerät unter verschiedenen Namen anlegst und ein Timer aktiv auslöst, d.h. der Zustand des Zielgeräts wird verändert, dann werden auch eventuell schlummernde Timer beendet._

Damit wolltest Du mir wahrscheinlich sagen (und ich habe es erst heute nach dem erfolglosen Testen verstanden), dass ich zwar die Programmierung damit umgehe (also mehrere Timer starten), es aber letztendlich doch nicht klappt, da Timer dann beendet werden, wenn sich der Status am Zielgerät ändert, was ja trotz Alias dasselbe bleibt, oder?

Letztendlich war es bei meinem Test so, dass beide Timer gestartet sind und als einer der Timer gegriffen hat (Bedingungen erfüllt waren), BEIDE Timer beendet wurden, da das Zielgerät eine Veränderung erfahren hat. Somit hat mein Ansatz mit den Alias nicht zum gewünschten Erfolg geführt.

Ich glaube ich werde mich nun mal den Blockly Möglichkeiten widmen (neue Herausforderung) müssen, um meinen Anwendungsfall realisiert zu bekommen.

**Comment by gsicilia82** [comment]
Wenn du einzelne Geräte speziell ansteuern möchtest, sollte es mit Blockly keine Probleme geben.
Ich hätte dein spezielles Problem gelöst, indem eine Szene für "Niemand Daheim" und eine weitere Szene für "Jemand kommt heim" erstellt hätte. Komplett unabhängig von irgendwelchen Timern sehe ich hier gute Komfortgewinne. Wenn ich heim komme und es dunkel ist, geht sofort das Licht im Flur an, das Licht im Wohnzimmer geht auch an und nach 2 Minuten wieder aus, wenn dort zwischenzeitlich kein BWM reagiert hat.

Viel Erfolg und auch dir ein Dank für das Melden vom Bug.
