### ISSUE TITLE
Wie sind die Bedingungen verknüpft / verknüpfbar? 

### ISSUE THREAD

**Issue by WorldNavigator** [gsicilia82/Timer_iobroker#7]
Hi giuseppe,
ich habe lange gesucht nach einer Möglichkeit Timer aus Vis zu verwalten. und deine Möglichkeit ist genau was ich suchte. super.
ich habe allerdings schwierigkeiten mit den Bedingungen. 
ich möchte eigentlich nur einen programmierten Timer beenden wenn zwei Temperaturwerte über 1 Grad sind.
lässt sich das direkt in Vis verknüpfen oder muss ich ein Script basteln?
sg Mischelle

**Comment by gsicilia82** [comment]
Freut mich, wenn das Script weiterhin Anwendung findet.
Wenn ein Timer im Hintergrund wartet, bis Bedingungen erfüllt werden, wird dieser dadurch vollständig beendet, wenn das Zielgerät geändert (oder aktualisiert?) wird.
Die zweite Möglichkeit, einen Timer zu beenden: wenn der nächste Timer des selben Zielgeräts zeitlich aktiviert wird. Daher ist deine Aufgabenstellung nicht möglich.

Kurz:
Mit Bedingungen etwas steuern klappt, mit Bedingungen einen Timer im Hintergrund löschen, das geht nicht. 

Vieles ist darauf ausgelegt, dass ein einziger Timer pro Gerät aktiv ist. Daher wäre es nicht ohne weiteres möglich, es zu erweitern. 

Evtl könntest du etwas ausrichten, wenn du das Skript auf einer weiteren Instanz laufen lässt und das selbe Zielgerät von Instanz 0 steuerst. 

Wenn du das Skript aber nur für einen einzigen Timer benötigst, wäre es wahrscheinlich overkill. 

Gruß, Giuseppe 


Edit:
Das Skript kann auch in der selben Instanz mehrfach verwendet werden. Es muss nur der Hauptname "Timer" geändert werden. Das Mainview müsste dann nochmal kopiert werden. Das view vom Editor muss nicht kopiert werden

**Comment by gsicilia82** [comment]
Es gibt im Timer die Möglichkeit als Sollwert "Reset" vorzugeben. Der zeitliche Trigger von diesem Aufruf führt dazu dass ein vorhandener Timer im Hintergrund sofort gelöscht wird. Ich schaue mir das heute Abend an, ob ich das optimieren kann, sodass zunächst die Bedingungen erfüllt sein müssen.

**Comment by WorldNavigator** [comment]
Danke dir.
jetzt schreib ich dir mal was ich eigentlich machen will.
![image](https://user-images.githubusercontent.com/16295713/213125549-58c571f9-5c6f-4f44-a15b-2ac5d14510cb.png)

Die Poolpumpe läuft im Winter nachts um 22:26 los per fixem Timer und soll nach der goldenhour wieder ausschalten AUSSER die Temperatur mindestens eines von zwei Temperaturfühlern ist kleiner 1 Grad. 

dann könnte ich noch eine Stunde später wieder einen AUS Timer aktivieren (evtl mit der gleichen Bedingung)

**Comment by WorldNavigator** [comment]
hallo Giuseppe,
ich habs jetzt mit einem simplen script gelöst das einen State mit dem Ergebnis beschreibt das dann die Bedingung für den Timer ist.
Script:
 setState("0_userdata.0.Test.testTimerBedingung", (getState("hue.0.Hue_outdoor_temp._sensor_1.temperature").val < 1 || getState("viessmannapi.0.26878.0.features.heating.sensors.temperature.outside.properties.value.value").val < 1));
und im timer_iobroker definiere ich einfach z.B. alle Stunde nen Aus-timer mit der gleichen Bedingung.
![image](https://user-images.githubusercontent.com/16295713/213245390-f23473ba-ded8-45be-9d75-93f54f9d5272.png)

**Comment by WorldNavigator** [comment]
das ist ok für meine Anwendung.

**Comment by gsicilia82** [comment]
Klasse, dass es mit einem Workaround geklappt hat. Habe mich eben wieder in das Skript "eingelesen". 
Bisher ist die Liste mit den Hintergrund-Timern ein JSON mit einfachen Zuweisungen, wie z.B. hier zu sehen
`{"Licht Flur":1,"Licht Kueche":0}`
Jede Nummer entspricht einem klar definiertem Timer. Jedes Gerät beginnt bei 1, 21, 41 usw. Somit können bis zu 20 Timer pro Gerät klar zugeordnet werden.
Ich müsste "nur" die einfache Zuweisung einer Zahl zu einem Array umfunktionieren. Wenn "Reset" als Timer aktiviert wird, wird diese Timernummer dem Array hinzugefügt, statt den alten Timer zu ersetzen. Leider wird das Objekt `subscribesList` 24x im Skript verwendet; hier müsste überall das Array abgefragt werden, statt der einfachen Zahl.

**Comment by WorldNavigator** [comment]
ok. da ist für mich auf jeden Fall mein Workaround flexibler zumal ich auch die Bedingung mit allen Verknüpfungen einfach im Griff habe.
Danke dir.

**Comment by gsicilia82** [comment]
Ich glaube gerade gemerkt zu haben, dass du kein zusätzliches Skript benötigt hättest. Evtl sind auch die Vielzahl von AUS Timer nicht nötig, wenn deine Aufgabenstellung wie folgt umgeschrieben werden kann:

Wenn die Pumpe läuft, soll diese nach frühestens einer Stunde ausgeschaltet werden oder zu einem späteren (beliebigen) Zeitpunkt wenn zwei Temperaturen über 1 Grad sind. 

Du könntest einen einzigen AUS Timer eine Stunde nach AN setzen und beide Temperaturen auf über 1 Grad prüfen. Je Temp Temperatur Sensor eine Bedingung. Der Schalter "Timer merken" sollte natürlich aktiviert werden.

Damit die Pumpe nicht ewig läuft, sollte natürlich irgendwann ein AUS Timer definitiv greifen.
