### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by mbefore305** [gsicilia82/Timer_iobroker#8]
See attached screenshot from adapter installation.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/6396795/218315733-e52ccd6c-45a8-46b4-87da-e6cea445e799.png">

**Comment by gsicilia82** [comment]
It is a Script, not an Adapter. Please, read Readme for instructions.

**Comment by mbefore305** [comment]
Stupid me. Sorry!
